### ISSUE TITLE
Add notes on ssh

### ISSUE THREAD

**Issue by henrykironde** [datacarpentry/organization-genomics#106]
I think it would be nice to add some setup notes on ssh.

**Comment by hoytpr** [comment]
Hi @henrykironde and thanks for the suggestion! Which lesson in organization genomics do you feel like would be using SSH? Are you thinking about using the SRA Toolkit or using SSH to access NCBI or ENA?

**Comment by henrykironde** [comment]
Hi @hoytpr, I think the scientists was missing the setup of putty.  https://datacarpentry.org/cloud-genomics/02-logging-onto-cloud/index.html.
It worked well after and I think we can close this.

**Comment by hoytpr** [comment]
I see, well thanks anyway and have a great week! Really trying to put this lesson in good shape.
