### ISSUE TITLE
Typo in the common problems section

### ISSUE THREAD

**Issue by ousodaniel** [datacarpentry/organization-genomics#111]
#Please delete the text below before submitting your contribution. 

---
The line "...help with this lesson and **_tell how people_** to do things in the other OS." Should read "...help with this lesson **_and tell people how_** to do things in the other OS."
---

**Comment by hoytpr** [comment]
Thanks @ousodaniel for catching this! Would you like to try and put in a pull-request to fix it? If not, I can probably get to a little later. 

Peter

**Comment by ousodaniel** [comment]
Hi Peter,

I'll do that next week, on holiday. Thanks

Cheers,
Ouso

**Comment by ErinBecker** [comment]
I think this has been fixed now, right @hoytpr?

**Comment by hoytpr** [comment]
Yes, thanks @ErinBecker
