### ISSUE TITLE
Combine Data Tidiness and Planning for NGS

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [datacarpentry/organization-genomics#112]
Arizona BBQ Team: There may be some opportunities for combining these two sections. The spreadsheet with the current data set is good, and should be used so we don't need a second spreadsheet exercise (sample submission) - maybe some of those discussion questions can be moved over.

**Comment by hoytpr** [comment]
Jason, I believe we're good with this lesson and the genomics lessons.
