### ISSUE TITLE
Combine (and reduce) the SRA Lesson

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [datacarpentry/organization-genomics#113]
Arizona BugBBQ - The SRA lesson is too much and the subject matter is too deep to cover well. We suggest showing an SRA submission spreadsheet in the tidiness section. Learners could browse this is a short exercise and be made aware that this is probably metadata they will need to collect.

**Comment by hoytpr** [comment]
Hi @JasonJWilliamsNY and thanks for the suggestion. "We" agree, and have a plan to work on this now, potentially by using an "extra" page where those interested can learn more about finding data on NCBI. Combining metadata collection for SRA submission is included in the plan.  I'm going to put this up as a project for this repo. Thanks!

**Comment by hoytpr** [comment]
I'm reopening this because when it's closed it get overlooked.

**Comment by ewallace** [comment]
I taught this lesson this morning and I like it as-is, I don't think it's too much. Repeating the "tidiness" on the Tenaillon in Discussion 2, and then separately on the SRA submission spreadsheet helps to reinforce those lessons. Especially for a mixed group of learners, for some of whom this thinking was completely new. We skipped some optional parts but brought the lesson in at 1hr50mins including a 15min coffee break, and breakout rooms for online teaching.
