### ISSUE TITLE
clarification

### ISSUE THREAD

**Issue by ousodaniel** [datacarpentry/organization-genomics#115]
Please delete the text below before submitting your contribution. 

---

In the episode _### "Planning for NGS project"_ the sub-heading _### "Retrieving samples from the facility"_ may factually confuse, for clarity, I suggest _"Retrieving sample **sequencing data** from the facility"_. The change will address both the aspect of seq files and seq-file-metadata, otherwise, as is, it insinuates that we are getting back the sample.

---

**Comment by hoytpr** [comment]
I agree with you @ousodaniel, As someone who runs a sequencing lab, I should have caught that myself! Would you like to submit a pull-request for that?
