### ISSUE TITLE
Lesson 3 REL4541B instructions no longer work as-written

### ISSUE THREAD

**Issue by rltillett** [datacarpentry/organization-genomics#121]
In Lesson 3, the instructions to get to REL4541B are no longer valid. I just looked and it appears that pull request #120 also contains a proposed a solution to this issue. My proposition is slightly different, and might reliably still point the students to the REL4541B (SRR2591054) run that the lesson currently intends to cause them to examine, which might be a bonus if the particular run is meaningful to the lesson.

Where the current lesson instructs

> Click on the Run Number of the first entry (REL4541B). This will take you to a page that is a run browser. Take a few minutes to examine some of the descriptions on the page.

Modified instructions that should work (at least until the next visual redesign by NCBI) might read like this:

> Scroll down to the list of Runs in this SRA Project. Let's try to find a particular run in this large project. Look for a run with Library Name "REL4541B." Try searching for the Library Name in the search box with the orange tag on it, and click Run SRR2591054 from the two results returned.

**Comment by hoytpr** [comment]
Hi @rltillett and thanks! Could you and [@laninsky](https://github.com/laninsky) work together for this PR? I tried the search and because it works, it does seem like the best option for maintaining consistency in the workshop. It also demonstrates the search function... which is cool.
