### ISSUE TITLE
Locate the Run Selector Table for the Lenski Dataset on the SRA does not work with IE

### ISSUE THREAD

**Issue by aschuerch** [datacarpentry/organization-genomics#124]
@bvreede noticed when helping one of the participants that downloading the run selector table does not work with Internet explorer

**Comment by hoytpr** [comment]
HI @aschuerch and thanks for bringing this up. I just checked and IE does act strangely, but basically, if you open the downloads menu in IE, it says the file is "waiting to download". You then can click on "Save" or "Save as...' and the file will download normally.  I'm not sure why IE has this behavior. If you want to send a PR detailing the IE download procedure, it seems reasonable to include it. 

![image](https://user-images.githubusercontent.com/5910884/69548541-2710a980-0f5d-11ea-87cf-2582bf4bae5d.png)

**Comment by aschuerch** [comment]
Thank you for the quick comment @hoytpr ! Good to hear that there is a workaround. I myself do not have access to IE, but maybe @bvreede is willing to put in a PR?
