### ISSUE TITLE
_episodes/03-ncbi-sra.md NCBI SRA dowload workflow error

### ISSUE THREAD

**Issue by molikd** [datacarpentry/organization-genomics#125]
Hello! 

I noticed that the workflow for students here: https://github.com/datacarpentry/organization-genomics/blob/gh-pages/_episodes/03-ncbi-sra.md 

for the "Download the Lenski SRA data from the SRA Run Selector Table"

Portion of the lesson is now out-dated due to the recent NCBI upgrade 

see:

https://trace.ncbi.nlm.nih.gov/Traces/study/?acc=SRP064605&o=acc_s%3Aa

-Dave

**Comment by hoytpr** [comment]
Hi @molikd thanks for the heads up. Do you want to put in a PR?  That would be great!

**Comment by molikd** [comment]
submitted #126 for approval.

**Comment by hoytpr** [comment]
Looks good to me. Will wait a few days for other maintainers to follow up. Thanks @molikd !

**Comment by hoytpr** [comment]
closing #126
