### ISSUE TITLE
Some issues https://datacarpentry.org/organization-genomics/02-project-planning/index.html

### ISSUE THREAD

**Issue by waydeveldman** [datacarpentry/organization-genomics#139]
Under https://datacarpentry.org/organization-genomics/02-project-planning/index.html:
1) This question in the exercise is not clear: If you wanted to relate file names to the sample names submitted above (e.g. wild type…) could you do so?
2) This answer to this question needs to mention forward and reverse: What do the _R1/_R2 extensions mean in the file names?

**Comment by JCSzamosi** [comment]
Thanks for your feedback, @waydeveldman. I agree that these changes would be a good idea. I'm opening up a pull request to clarify these exercises, and I'll link it here
