### ISSUE TITLE
Updates required in ‘Examining Data on the NCBI SRA Database’

### ISSUE THREAD

**Issue by achilleosk** [datacarpentry/organization-genomics#147]
I think this section is very good and informative, but it needs a few updates. See below. 

Section: “Accessing the original archived data”
Point 2: The project now shows 15 instead of 14 sub-projects 

Section: "Download the Lenski SRA data from the (newer) SRA Run Selector Table"
Point 2: I don't think the option to switch back to the “old Run Selector” exists anymore, in which case the note after point 6 and comments about the 'old Run Selector' throughout the page is not necessary.
Point 4: The screenshots of the SRA website are also outdated.

Section: “Review the SraRunTable in a spreadsheet program”
When opening the file in excel the information is not separate by columns. Each entry is one single line, and this doesn't change if I rename the file before importing it to excel. Please note that I also used the new SRA Run Selector to download the file. 
I suggest that this section might need an extra step for showing how to convert text to columns by using a comma delimiter. Otherwise, it is not easy to read the information in the SraRunTable. 

Section: “Where to learn more” and “About the Sequence Read Archive”
It mentions (and it is so true) that "The best way to transfer a large SRA dataset is by using the SRA Toolkit", but it doesn't say anything else. When following the 'SRA Toolkit' link it is very informative, but I think it can be a bit overwhelming for a beginner. 
It might be worth adding a section about the SRA Toolkit and include information specifically on how to use prefetch and fasterq-dump to extract FASTQ-files from SRA-accessions.

**Comment by hoytpr** [comment]
Wow @achilleosk that's a great contribution. Thanks very much! This lesson will be one that constantly changes so input is appreciated. I'm going to change the 14 to 15 immediately and trim the language about the "old run selector" I will check the screenshots also.  That text file has been problematic for a while so I'm going to download it and see if we can make it work. Sometimes renaming the file to ".tsv" will work.  

Are you comfortable enough with Github to produce a Pull Request? If you are familiar with the SRA Toolkit, You might submit some examples as "Issues" and then after review they might make great additions to the lesson. We generally do not have extra time in workshops, but I agree it would be an important item to learn. This might be turned into an optional lesson/subject.

**Comment by hoytpr** [comment]
Done but will require monitoring.
