### ISSUE TITLE
Suggestion for page: Project Organization and Management for Genomics: Data 

### ISSUE THREAD

**Issue by chris-owen** [datacarpentry/organization-genomics#148]
This small suggestion is to correct the in-text citation. It currently reads, 'In Tenaillon et al 2016...', while the in-text citation should look something like this, 'Tenaillon et al. (2016)'.

**Comment by hoytpr** [comment]
You are correct @chris-owen . Nice of you to contribute! Would you like to submit a pull request (remember NOT on the gh-pages branch) or shall I make the changes?

**Comment by hoytpr** [comment]
Current wording looks okay to me.
