### ISSUE TITLE
Links need to be fixed in CONTRIBUTING.md

### ISSUE THREAD

**Issue by tobyhodges** [datacarpentry/organization-genomics#154]
The Contributing Guide, `CONTRIBUTING.md`, contains two links with URLs that should be updated:

1. the _How to Contribute to an Open Source Project on GitHub_ link leads to a 404 and should be updated to link to https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github
2. the `[repo]` link reference currently points to a placeholder URL (https://example.com/FIXME) and should be updated to point to the source repository for the lesson (i.e. this GitHub repository).

The Contributing Guide is one of the files that is unique to each repository - to allow for individual lesson projects to define their own guidance for contributors - so unfortunately this is not an issue that can be fixed centrally e.g. by updating the template files in the lesson infrastructure. Instead the file must be updated in the individual lesson repositories themselves.

**Comment by JCSzamosi** [comment]
Thanks for opening this, @tobyhodges. I'll do a pull request today to fix it. Any objection to me fixing both in a single PR?

**Comment by JCSzamosi** [comment]
While I'm looking at this, I notice that the link labelled "creating an issue" links not to the issues tab, but to a list of existing, open Carpentries issues. This seems confusing to me, since it doesn't actually show the reader how to create new issues. I wonder if this list should be linked from the third bullet (creating a pull request), and a link to the issues tab added to the second bullet?

**Comment by tobyhodges** [comment]
Not at all. I think they make sense as a single PR

**Comment by tobyhodges** [comment]
And I agree with your comment about the link to the Help Wanted Issues listing. If you'd like to also adjust that wording, please do - if you want to do it in the lesson infrastructure templates for this file, so that the change is reflected in all future repositories as well, that would be even better

**Comment by JCSzamosi** [comment]
That sounds like a good plan. Do I need to include that third change in this PR as well, or does it suffice to do it in the infra template? It seems like it will need to be changed piecemeal for existing repositories, yes?

**Comment by tobyhodges** [comment]
I'm afraid that's right, yes.
