### ISSUE TITLE
Adding images for genomic standards warm-up exercise

### ISSUE THREAD

**Issue by debpaul** [datacarpentry/organization-genomics#16]
![ggbnbylabel](https://cloud.githubusercontent.com/assets/2990155/6986653/689377b4-da0d-11e4-9272-e7c45a4b465b.png)
![ggbnbyconceptname](https://cloud.githubusercontent.com/assets/2990155/6986656/6e8052be-da0d-11e4-9718-72fce5bfe155.PNG)

**Comment by ErinBecker** [comment]
This exercise is no longer part of the lesson. Closing here.

**Comment by ErinBecker** [comment]
@tracykteal  - Please let me know if I'm wrong and this issue should be reopened.
