### ISSUE TITLE
project organization guidelines and examples

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/organization-genomics#26]
In this lesson we make some recommendations around project and data organization. We will likely want to be sticking with recommendations, because every project is different, but maybe we could have more a list of guidelines, or some examples of how projects are organized.

We get comments that people are "still trying to get their head around how to organize data"

**Comment by mkuzak** [comment]
This looks like a different issue than #27 with the same name. Maybe we can rename it to "project organisation guidelines and examples"

**Comment by tracykteal** [comment]
With this current release, this will still be an outstanding issue.

**Comment by hoytpr** [comment]
@tracykteal @mkuzak @ErinBecker @fmichonneau If learners are having trouble with this lesson, more inline images as suggested in [#27](https://github.com/datacarpentry/organization-genomics/issues/27) would help. Using a single experimental example for SampleSheet and output might create a better flow from planning and organizing to output.
