### ISSUE TITLE
recommendations on project organization

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/organization-genomics#27]
This issue is for things people have learned on this lesson

Comments

"PIs should require not just end results, but the whole path and parameters to it"

"I wish I had taken this workshop earlier. Deciding how to save and manage dat is one big lesson learned the hard way!"

**Comment by ErinBecker** [comment]
@tracykteal - I'm really not sure what this issue is asking for. Could you please clarify what the desired enhancement looks like and what the process would be for putting it in place?

**Comment by Tantoluwa** [comment]
kindly provide the solution to the question raised

**Comment by ErinBecker** [comment]
Thanks @Tantoluwa! I've noted your comment in your instructor profile.

**Comment by NoushinN** [comment]
Great workshop topic, thank you. I think if the visualization (png) files are incorporated right beside the codes they are pertaining to, it would be easier to follow as opposed to them having their own section.

**Comment by ErinBecker** [comment]
Closing this issue as out of date.
