### ISSUE TITLE
setup missing

### ISSUE THREAD

**Issue by mkuzak** [datacarpentry/organization-genomics#30]
The file describing the setup should be present at http://www.datacarpentry.org/organization-genomics/setup.md
Maybe we only need one setup for all genomics lessons (something to think about discuss).

**Comment by smcclatchy** [comment]
Hi @mkuzak,

I had a similar thought while working on issues for [shell-genomics](https://github.com/datacarpentry/shell-genomics/issues/36). Do we want separate setup instructions for each, or one consolidated setup document that would ask participants to install R, git-bash, etc?

**Comment by mkuzak** [comment]
Yes, I would like that. One set of instructions with choices based on particular versions of the workshop. Learners may not know what they need for particular version but we could guide them. For example "If you are attending R version of the workshop you will need to install following software/RStudio"

**Comment by ErinBecker** [comment]
Creating a meta-issue in genomics-workshop for these issues and closing here.
