### ISSUE TITLE
Instructor notes link missing

### ISSUE THREAD

**Issue by sstevens2** [datacarpentry/organization-genomics#32]
[Notes for instructors link](http://www.datacarpentry.org/organization-genomics/guide/) is empty.

**Comment by mkuzak** [comment]
Yes. The _estras/guide.md file needs filling in and the link needs to be updated.

**Comment by ErinBecker** [comment]
We have some content in the instructor notes, but it's not up to date with our template for instructors notes, so I'll leave this open and tag for after this lesson release.

**Comment by NoushinN** [comment]
Hi there! I am really interested in this lesson, however, the after-lesson-release notes says "no results matched your search" same as "instructor guide"

**Comment by ErinBecker** [comment]
See https://github.com/datacarpentry/organization-genomics/pull/96

**Comment by hoytpr** [comment]
closes #32 and #96
