### ISSUE TITLE
Quick jump into shell commands

### ISSUE THREAD

**Issue by sstevens2** [datacarpentry/organization-genomics#33]
In 02-organization we start using shell commands without opening or introducing the terminal.  And then the command are just used and not explained.  It is a bit unclear to me if we are expecting them to know the shell commands or not because it says we will introduce you to these commands and then it seems like we expect them to have done the shell lesson before.

I suggest:
- Adding in opening terminal/gitbash
- A bit of introduction on the power of working in the shell
- Link to SWC shell lesson for more info
- Introduction to `mkdir` before using it
- Short explanation of `ls` before using it
- Short explanation of `nano` before using it 
- Adding more motivation for why you want to setup the project directory this way and what each of the folders will hold.

OR

- Writing in more expectations of knowing the commands instead of saying we are introducing them to these commands

**Comment by mkuzak** [comment]
Thank you. I agree. In the end, it will depend on the order of the lessons in the genomics workshop. In my opinion, the shell lesson [shell lesson ](https://github.com/datacarpentry/shell-genomics) should come first and learners should be already familiar with the commands used.
Adding motivation for the setup is important and I think should be the separate issue. Can you make one?

**Comment by sstevens2** [comment]
Sure I can make that a separate issue.  

I see what you mean about order.  I started looking through them in the order they are listed [here](http://www.datacarpentry.org/lessons/#genomics-workshop).  Maybe the order of the lessons overall needs to be clarified?

**Comment by mkuzak** [comment]
Yes, please separate issue would be great :). #35 
You're right about the order in the lesson overview. I think we were planning to have separate repositories connecting the lessons depending on the version of the workshop. There the lessons would be in the order they are actually taught. This is definitely something we need to know before deciding on those changes.

**Comment by ErinBecker** [comment]
Thanks for your comments @sstevens2. We've since moved the project organization episode into the shell lesson: http://www.datacarpentry.org/shell-genomics/06-organization/. This way, we can ensure that the learners have the necessary background for understanding the shell commands before diving into setting up a working directory.
