### ISSUE TITLE
Lang cleanup in introduction

### ISSUE THREAD

**Issue by sstevens2** [datacarpentry/organization-genomics#34]
Lesson 02-organization needs some cleanup of language.

'You should approach your sequencing project in a very similar way to how you do a biological experiment, and ideally, begins with experimental design.', this sentence is confusing right now, I'd suggest 'You should approach your sequencing project similarly to how you do a biological experiment and this ideally begins with experimental design.'

'Genomics projects can quickly accumulates hundreds of files across tens of folders.', accumulates --> accumulate

'Similarly, you probably won’t remember whether your best alignment results were in Analysis1, AnalysisRedone, or AnalysisRedone2; or which quality cutoff you used.' I suggest more options e.g. best alignment results, quality cutoff, version of software, settings for the software you used, etc.  But this isn't really a necessary change.

Also typo here:
‘\^X’, needs to have the '\' removed.

**Comment by ErinBecker** [comment]
Thanks @sstevens2!
