### ISSUE TITLE
01-introduction and 05-ncbi-sra paper reference links broken

### ISSUE THREAD

**Issue by murraycadzow** [datacarpentry/organization-genomics#36]
The links for the Blount et al 2012 paper and supplementary are broken in both 01-introduction.md and 05-ncbi-sra.md

**Comment by mfoos** [comment]
I started to work on this, with just the PubMed URL linking to PMC free download, but now am thinking there should maybe be a discussion about PDF vs PubMed. I'm going to finish the PR and we can just not accept it if that's the decision.

**Comment by mkuzak** [comment]
Fixed by @mfoos in #38
