### ISSUE TITLE
Re-configuring this lesson

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/organization-genomics#40]
In this issue I'm proposing a reorganization of this module and some changes in the lessons. 

### General idea for Genomics Organization Introduction 

Organizing a project that involves sequencing involves many components. There's the start of the experiment, with the records of the experimental setup and conditions, as well as the sequencing information and the records of the bioinformatics analyses. It's an extension of your lab notebook and freezer samples to digital data and analyses. In this lesson, we'll go through the project organization and documentation that will make your current life more organized and easier for future you to understand what was done.

In this lesson you will learn:

1. how to structure your metadata, tabular data and information about the experiment. The metadata is the information about the experiment and the samples you're sequencing.
2. how to prepare for, understand and organize and store the sequencing data that comes back from the sequencing center
3. how to access and download publicly available data that may need to be used in your bioinformatics analysis
4. the concepts of organizing the files and documenting the workflow of your bioinformatics analysis

---

With this structure, I'm proposing to re-order and expand some of the existing lessons

- Move 04-data-tidiness to the first lesson and expand the discussion of metadata
- Move 03-project-panning to the second lesson and adding a discussion of data storage and importance of keeping raw data raw
- Move 05-ncbi-sra to the third lesson and adding a general discussion of publicly available data
- Move 02-organization to the fourth lesson and rather than doing the command line discussion and exercises (since we're not on the the cloud yet to have access to the command line), focusing on the concepts of documenting and managing files in a bioinformatics workflow, particularly the branching workflow and exploring parameter space

Before working on this re-configuration, I wanted to get thoughts on this idea from other maintainers and genomics folks. Thanks!

@ErinBecker @mkuzak @Roselynlemusinmegen

**Comment by ErinBecker** [comment]
Thanks for the thoughts @tracykteal. I like this reframing and your new structure. I especially like the expansion of the "how to access publicly available data" episode.

I wanted to add a note for you that we do have a section in the shell lesson now about keeping raw data raw and enforcing this with permission settings. http://www.datacarpentry.org/shell-genomics/03-working-with-files/

**Comment by tracykteal** [comment]
Thanks. I'll continuing working on the reorganization. Thanks for the pointer on the shell lesson. I'll see what's there, so I don't make redundant information.

**Comment by ErinBecker** [comment]
@tracykteal - I know that you've done a lot of work on this lesson in the last few days. Could you please let me know if that work closes this issue?

**Comment by tracykteal** [comment]
Sorry, just looping back. Yes, this reorganization has been finished, so closing.
