### ISSUE TITLE
Edit/Comment the introduction

### ISSUE THREAD

**Issue by ACharbonneau** [datacarpentry/organization-genomics#5]

**Comment by mkuzak** [comment]
Hi @ACharbonneau what kind of edit/comments are you thinking of? Is it about general improvements to the introduction episode?

**Comment by ACharbonneau** [comment]
Hey, that's a label I made when we were creating the repo. It was just a place I wanted copy-edited and whatnot. I'm sure it's entirely different at this point, and you can probably ignore any of my old comments.

**Comment by mkuzak** [comment]
No worries, thank you for the clarification. I will close this issue.
