### ISSUE TITLE
Documenting your commands using "history"

### ISSUE THREAD

**Issue by destadey** [datacarpentry/organization-genomics#72]
Next to the section that describes the command history:

![image](https://user-images.githubusercontent.com/7845950/48986978-ae99c180-f12b-11e8-8cb2-95f573eadcfa.png)

What if we mention the two redirection operators ">" and ">>" instead of mentioning the latter only? Using the command "$ history > dc_workshop_log_xxxx_xx_xx.sh", we can create a new file with the name dc_workshop_log_xxxx_xx_xx.sh which is not appendable as we move on to use more commands.

**Comment by hoytpr** [comment]
Hi @destadey and thanks for your comments. Unfortunately you may have entered these issues in the wrong lesson. It looks like you are working in a Jupyter (iPython) notebook. I'm sorry I wasn't able to locate the exact lesson you are commenting about. Should I go ahead and close this issue and you can place it in a different lesson?
Thanks!
Peter

**Comment by hoytpr** [comment]
Closing #72
