### ISSUE TITLE
CSS not displaying on the Setup page

### ISSUE THREAD

**Issue by tstilwel** [datacarpentry/organization-genomics#75]
The CSS isn't working at the following link:

https://datacarpentry.org/organization-genomics/setup/

If I use check with a CSS validation tool (http://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fdatacarpentry.org%2Forganization-genomics%2Fsetup%2F&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en), I see the following errors: 

File not found: https://datacarpentry.org/organization-genomics/setup/assets/css/bootstrap.css: Not Found 
File not found: https://datacarpentry.org/organization-genomics/setup/assets/css/bootstrap-theme.css: Not Found 
File not found: https://datacarpentry.org/organization-genomics/setup/assets/css/lesson.css: Not Found 
File not found: https://datacarpentry.org/organization-genomics/setup/assets/css/syntax.css: Not Found

**Comment by hoytpr** [comment]
Thanks very much for finding this! Needs to be fixed asap.  I'm not a CSS guru so @raynamharris @analeighgui @mkuzak @Roselynlemusinmegen : help needed.

**Comment by hoytpr** [comment]
Looks like this is similar to issue #73 and a fix using `relative_root_path` was performed as seen at:
[THIS PAGE.](https://github.com/datacarpentry/python-ecology-lesson/commit/39ed62b9b218242775b043e9eff3e76bb430602d#diff-f82a4c1c005f3128094642254b554892)

@tstilwel do you feel comfortable making a PR that could fix this?

**Comment by tstilwel** [comment]
I'll give it a shot.  Thanks!

**Comment by hoytpr** [comment]
fixed by #77
