### ISSUE TITLE
file download missing in 01-data-tidiness

### ISSUE THREAD

**Issue by taylorreiter** [datacarpentry/organization-genomics#80]
The link to download the file in the last exercise of 01-data-tidiness is missing. The file is located at https://github.com/datacarpentry/organization-genomics/blob/gh-pages/files/Ecoli_metadata_composite_messy.xlsx

**Comment by hoytpr** [comment]
Hi @taylorreiter, thanks for the heads up. The Ecology spreadsheets lesson hasn't been updated yet, and These changes will need to be incorporated into Ecology Spreadsheets, Nonetheless, if you want to put in a PR for this, and for #81 it would be great.

**Comment by taylorreiter** [comment]
Hi @hoytpr! I'm not sure what you mean by the Ecology spreadsheet lesson/incorporating to the Ecology spreadsheets. Would you be willing to clarify a bit?

Also, I'm teaching this workshop today with @svigneau...we'll be putting in some more issues for things we notice along the way!

**Comment by hoytpr** [comment]
@taylorreiter 
https://datacarpentry.org/spreadsheet-ecology-lesson/
This lesson might be becoming/already obsolete. Nobody tells me anything. :-)

**Comment by taylorreiter** [comment]
Ah! Ok. I'm referencing this exercise:

```
This is some potential spreadsheet data generated about a sequencing experiment. 
With the person next to you, for about 2 minutes, discuss some of the problems with the 
spreadsheet data shown above. You can look at the image, or download the file to you 
computer via the link and open it in a spreadsheet reader like Excel.
```

We updated the png to a new dataset yesterday. The new messy spreadsheet matches the new dataset that is used in the `wrangling-genomics` episode, and which was approved by the CAC (see https://github.com/datacarpentry/wrangling-genomics/pull/133). 

I missed adding a link to download what is shown in the png to the local computer. Additionally, the wrong cleaned data sheet is currently linked. The clean data sheet is here: https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/files/Ecoli_metadata_composite.tsv. 

This is separate from the Ecology lesson.

**Comment by hoytpr** [comment]
Thanks @taylorreiter I'm just gonna close the issue #80
