### ISSUE TITLE
should we add a picture from the Tenaillon et al. paper demonstrating how to find SRA accessions?

### ISSUE THREAD

**Issue by taylorreiter** [datacarpentry/organization-genomics#82]
@jessicamizzi and I thought it would be nice to show a png from the Tenaillon et al. paper (where the data for the `wrangling-genomics` lessons was first sequenced) where the SRA accession or project number can be found. This would demonstrate one way to interact with data: read a paper, find accession number in paper, look paper up on the SRA or ENA. We were unsure of copyright infringement on the original paper though. 

Thoughts?

**Comment by hoytpr** [comment]
The license suggests that more than 100 words, OR images, need permission.

**Comment by hoytpr** [comment]
So, the manuscript has specific restrictions on use, listed [HERE](https://www.nature.com/reprints/permission-requests.html). But it sounds like requesting to reuse an image in coursework is possible without a fee according to [THIS RIGHTLINKS PAGE](https://s100.copyright.com/AppDispatchServlet?author=Olivier%20Tenaillon%2C%20Jeffrey%20E.%20Barrick%2C%20Noah%20Ribeck%2C%20Daniel%20E.%20Deatherage%2C%20Jeffrey%20L.%20Blanchard%20et%20al.&contentID=10.1038%2Fnature18959&imprint=Nature&issueNum=7615&orderBeanReset=true&publication=Nature&publicationDate=2016-08-01&publisherName=SpringerNature&title=Tempo%20and%20mode%20of%20genome%20evolution%20in%20a%2050%2C000-generation%20experiment&volumeNum=536) from the article itself. Although I'm certain I am NOT the person to request this permission, the choices for essentially free and instant approval are shown in this image:


![nature-reuse-conditions](https://user-images.githubusercontent.com/5910884/53907181-4142da00-4012-11e9-8627-35027b55d124.jpg)

**Comment by taylorreiter** [comment]
Thanks for hunting this down @hoytpr! Would training materials be the right selection?

I filled out the necessary boxes from the link above and confirmed that reuse would be free. Who would be the proper person to obtain the license? Would it be @ErinBecker, @fmichonneau, or @tracykteal? Or someone else?

**Comment by hoytpr** [comment]
I think any of those fantastic individuals would be good choices, they should decide. 
Training materials seemed logical to me also. Also "coursepack/classroom".
Proper acknowledgment of the image is required also.

**Comment by ErinBecker** [comment]
Hi all - thank you @hoytpr and @taylorreiter for tracking down the permissions. I'm working on getting a license now and will update shortly.

**Comment by ErinBecker** [comment]
We now have the following license:

>> 

License Number | 4545971053629 |   |  
-- | -- | -- | --
License date | Mar 11, 2019 |   |  
Licensed Content Publisher | Springer Nature |   |  
Licensed Content Publication | Nature |   |  
Licensed Content Title | Tempo and mode of genome evolution in a 50,000-generation experiment |   |  
Licensed Content Author | Olivier Tenaillon, Jeffrey E. Barrick, Noah Ribeck, Daniel E. Deatherage, Jeffrey L. Blanchard et al. |   |  
Licensed Content Date | Aug 1, 2016 |   |  
Licensed Content Volume | 536 |   |  
Licensed Content Issue | 7615 |   |  
Type of Use | Training Materials |   |  
Requestor type | non-commercial (non-profit) |   |  
Format | electronic |   |  
Portion | figures/tables/illustrations |   |  
Number of figures/tables/illustrations | 1 |   |  
High-res required | no |   |  
Will you be translating? | no |   |  
Circulation/distribution | 10,001 to 20,000 |   |  
Author of this Springer Nature content | no |   |  
Title | Data Carpentry Project Organization and Management for Genomics |   |  
Client / Sponsor | The Carentries |   |  
Expected presentation date | Mar 2019 |   |  
Portions | We request to use in our training materials a screen capture of the portion of the methods section that shows the BioProject number associated with the data for this manuscript. This is to instruct on how to read a scientific manuscript. |   |  
Requestor Location | The Carpentries1000 Broadway Suite #480OAKLAND, CA 94607United StatesAttn: The Carpentries |   |  
Billing Type | Invoice |   |  
Billing address | The Carpentries1000 Broadway Suite #480OAKLAND, CA 94607United StatesAttn: The Carpentries |   |  
Total | 0.00 USD

Please see these terms and conditions: 

>> The Licensor's permission must be acknowledged next to the licensed material in print. In electronic form, this acknowledgement must be visible at the same time as the figures/tables/illustrations or abstract, and must be hyperlinked to the journal/book's homepage. Our required acknowledgement format is in the Appendix below.

>> For Journal Content:
Reprinted by permission from [the Licensor]: [Journal Publisher (e.g. Nature/Springer/Palgrave)] [JOURNAL NAME] [REFERENCE CITATION (Article name, Author(s) Name), [COPYRIGHT] (year of publication)

**Comment by hoytpr** [comment]
Awesome @ErinBecker. Thanks, @taylorreiter are you going to put in a PR?

**Comment by taylorreiter** [comment]
PR in at #98!

**Comment by hoytpr** [comment]
I believe we now agree there should be images. Closing #82
