### ISSUE TITLE
link broken to navigate to Tenaillon et al. data on SRA

### ISSUE THREAD

**Issue by taylorreiter** [datacarpentry/organization-genomics#83]
The link encoded here does not lead to the expected place

`1. Access the Tenaillon dataset from the provided link: https://trace.ncbi.nlm.nih.gov/Traces/study/?acc=SRP064605.`

**Comment by hoytpr** [comment]
The link:
https://trace.ncbi.nlm.nih.gov/Traces/study/?acc=SRP064605
Seems to have changed, but this has the "Run Table Button" requested in the next paragraph.
We will  need to change "Click on the first entry (REL4541B). "
to:
"Click on the first entry (SRR2591054)" to get to the run table (it is still sample REL4541B)
@taylorreiter

**Comment by hoytpr** [comment]
closed by PR#85. Thanks!
