### ISSUE TITLE
Missing Glossary

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/organization-genomics#93]
Glossary section of [reference page](https://datacarpentry.org/organization-genomics/reference.html) is "FIXME"

**Comment by hoytpr** [comment]
I did the forbidden and merged my own PR. Sorry but just trying to keep the issues and PRs clean. You can ban my privileges if needed.

**Comment by ErinBecker** [comment]
Thank you @hoytpr! No one will be banning your privileges for this! Thank you for taking care of this. Please let me know if you need / want more Maintainer support on your repo.
